language: java
branches:
  only:
  - master
  - develop
install: true
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
- git clone -b master https://github.com/nablarch/nablarch-ci-script.git $HOME/build-script/
  && chmod +x $HOME/build-script/travis-ci/*.sh
- $HOME/build-script/travis-ci/setup-oracle-jdk6.sh
- $HOME/build-script/travis-ci/prepare_travis_settings.sh
- $HOME/build-script/travis-ci/build-nablarch.sh -p ci
- $HOME/build-script/travis-ci/upload-test-report.sh -p dev-deploy
notifications:
  slack:
    secure: gwk/CShWsd/gswQd0rj+3+G9HAFXX2sCzftiGSQ6smSHZRzJysAm0nQmTxDCCcDaAwF8uCXPdDRBM16mZILS+n6uXR1mxcvDf4Jnlr+7brAik/37qzpK4UC31hVMp6okbi5pCrO5Ym3LIBsnJB6iGbpdBiAfp+YBE/qTkrMZAwcs3DDhsS6Ivm6cbJmjWTQaM//ZNrRo3287IDFxYLg3OD0MlDMYxibiLiijcDQavZOs7BrA+VqwC2saQQpbMyhKpPMQuV/id1wunRGdUEsd/9gzX9cKbS6TsEbP0oieZDCc2SA9pG61+PPhW7B5L4/1M+ctFZ7gsByDAtqCYvqCR/oqzGNw2jlbEfPkq7Hp3bn0WBSQdyg147OiBjE+k5nXMxY6CxZf02v5XnbqIzSjjps3T0LiGZ2TEOBxJlKxyivwJMvkgh+uRjZ+zmjzGFC/+yenKrw9J53SR/e7GDWo8dMeEKsbsm/1pgO3EjaVcbfen8H9N/nglsQzhxnz6XhlUcZxKRXNYDYLLUgBGbezSD6+SfCbzIp+OSn3rzIjYPUzSDUCY7fF0ip9j4NzEGA4Y/1Z6b/XZSnyiyGmpzB3DzDy1qdv3LhYpWoE6ZbwPr+T8Zd7/TU2qMa9TbTbGfymZKtIi6szKW6lOSMo1iewythS19uYOZyrT1J4IDyBbH8=
